CREATE DATABASE '127.0.0.1/3050:C:\Users\User\Desktop\Repositórios\AppPedidos\Database\APPORDERS.FDB'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 16384
DEFAULT CHARACTER SET ISO8859_1 COLLATION PT_BR;